name: MERN CI Pipeline

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ===== Backend =====
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: Backend/package-lock.json

      - name: Install backend dependencies
        working-directory: Backend
        run: npm ci

      - name: Run backend tests
        working-directory: Backend
        run: npm test

      # ===== Frontend =====
      - name: Install frontend dependencies
        working-directory: Frontend/crop-recomendation
        run: npm ci

      # - name: Run frontend tests
      #   working-directory: Frontend/crop-recomendation
      #   run: npm test
